# Generated by Django 3.2.7 on 2021-10-10 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': [('task_management', 'Can create, assign and delete tasks')]},
        ),
    ]
